### ISSUE TITLE
Create a viewable Grocery List

### ISSUE THREAD

**Issue by ahelsel** [Ahelsel/CSCI3308-017Team01Tigers#3]
As a user, I should be able to view a Grocery List on the screen that displays items on my grocery list in a readable format.

Acceptance Criteria: Have all items in a user's grocery list viewable on the screen in a readable format that is not cluttered

**Comment by ze3roop** [comment]
Now able to view groceries on the list, but only with a hard coded grocery_list_id at the moment.
